#!/bin/sh -efu

. "${0%/*}/squidmill-test-functions.sh"

DIR="${0%/*}"
PREFIX="${PREFIX:-${0##*/}}"
COUNT=5000
ROUND=600

# Cleanup
rm -f "$DIR/$PREFIX.squidmill.log" "$DIR/$PREFIX.db" "$DIR/$PREFIX.access.log"

# The test
print_log $COUNT >"$DIR/$PREFIX.access.log"

echo "Call squidmill in foreground to insert and round the written data"
echo "See $PREFIX.squidmill.log for details"
run_squidmill -D -d "$DIR/$PREFIX.db" -R $ROUND -L "$DIR/$PREFIX.squidmill.log" "$DIR/$PREFIX.access.log"

assert_written "$DIR/$PREFIX.access.log" -eq $COUNT

check_db_count "$DIR/$PREFIX.db" -eq $((COUNT - ROUND * (COUNT / ROUND))) 'access_log'
check_db_sum "$DIR/$PREFIX.db" 'size' -eq $((COUNT * SIZE)) 'access_log' 'hourly_log' 'daily_log' 'monthly_log'
