#!/bin/sh -efu

. "${0%/*}/squidmill-test-functions.sh"

DIR="${0%/*}"
PREFIX="${PREFIX:-${0##*/}}"
COUNT=10000
MAXNOINC=1000
MINQUERIES=2

# Cleanup
rm -f "$DIR/$PREFIX.squidmill.log" "$DIR/$PREFIX.squidmill.client.log" "$DIR/$PREFIX.db" "$DIR/$PREFIX.access.log"

# The test
print_log $COUNT 0 >"$DIR/$PREFIX.access.log"
assert_written "$DIR/$PREFIX.access.log" -eq $COUNT

echo "Call squidmill with SQL-server in background to insert the written records in follow mode"
echo "See $PREFIX.squidmill.log for details"
run_squidmill -D -d "$DIR/$PREFIX.db" -L "$DIR/$PREFIX.squidmill.log" -b "$DIR/$PREFIX.squidmill.pid" -c "$DIR/$PREFIX.squidmill.sock" -F "$DIR/$PREFIX.access.log"
pid=$(read_pid "$DIR/$PREFIX.squidmill.pid")
trap "terminate_squidmill $pid" EXIT HUP INT QUIT TERM

echo "Calling squidmill client in a loop until the expected summary values are reported"
echo "See $PREFIX.squidmill.client.log for details"
sum=0
queries=0
lastinc=0
while [ $sum -lt $((COUNT * SIZE)) ]; do
    report="$(run_squidmill -D -L "$DIR/$PREFIX.squidmill.client.log" -c "$DIR/$PREFIX.squidmill.sock" -r -S)"
    if [ $? -ne 0 ]; then
	echo "Squidmill query failed"
	exit 1
    fi
    queries=$((queries + 1))
    if [ -n "$report" ]; then
	new_sum="$(echo "$report" | cut -f2)"
	if [ $new_sum -gt $sum ]; then
	    sum=$new_sum;
	    lastinc=$queries
	elif [ $((queries - lastinc)) -eq $MAXNOINC ]; then
	    echo "Somethins goes wrong: no increase in summary size in $MAXNOINC queries"
	    exit 1
	fi
#	if [ $sum -lt $((COUNT * SIZE)) ]; then
#	    sleep 0.5
#	fi
    else
	echo "Null report"
	exit 1
    fi
done

if [ $sum -eq $((COUNT * SIZE)) ]; then
    echo "Summary size test passed"
else
    echo "Summary size test failed"
    exit 1
fi

if [ $queries -gt $MINQUERIES ]; then
    echo "Query count (concurrency) test passed: $queries queries were made"
else
    echo "Query count (concurrency) test failed: only $queries queries were made"
    exit 1
fi
