#!/bin/sh

LOGDIR=/var/log/squid
MILLDIR="$LOGDIR/squidmill"
MONTHLY="$MILLDIR/monthly.scm"
SUMMARY="$MILLDIR/summary.scm"

mkdir -p "$MILLDIR"
TMPFILE=`mktemp`
squidmill "$SUMMARY" "$MONTHLY" > "$TMPFILE"

mv "$TMPFILE" "$SUMMARY"
