#!/bin/sh

LOGDIR=/var/log/squid
MILLDIR="$LOGDIR/squidmill"
WEEKLY="$MILLDIR/weekly.scm"
MONTHLY="$MILLDIR/monthly.scm"

mkdir -p "$MILLDIR"
TMPFILE=`mktemp`
squidmill "$MONTHLY" "$WEEKLY" > "$TMPFILE"

mv "$TMPFILE" "$MONTHLY"
