#!/bin/sh
#
#
# chkconfig: - 90 25
# description: Online squidmill database update service

# Source function library.
. /etc/init.d/functions

PIDFILE=/var/run/squidmill.pid
LOCKFILE=/var/lock/subsys/squidmill
SQUIDLOGFILE=/var/log/squid/access.log
DBFILE=/var/log/squid/squidmill.db

start()
{
    start_daemon --pidfile "$PIDFILE" \
                 --make-pidfile \
                 --lockfile "$LOCKFILE" \
                 --displayname squidmill \
                 -- /bin/su -s /bin/sh -l squid \
                            -c "'/usr/sbin/squidmill -d \"$DBFILE\" -B 1 -F \"$SQUIDLOGFILE\"'"
}

stop()
{
    stop_daemon --pidfile "$PIDFILE" \
                --lockfile "$LOCKFILE" \
                --displayname squidmill \
                -- /bin/su
}

case "$1" in
    start)
      start
        ;;
    stop|condstop)
      stop
      ;;
    status)
        ;;
    restart|reload|condrestart|condreload)
        stop
        start
        ;;
    *)
        msg_usage "${0##*/} {start|stop|reload|restart|condstop|condrestart|condreload|status}"
        RETVAL=1
esac

exit $RETVAL
