#!/bin/sh -efu

SQUIDMILL="${1:-./squidmill}"
export SQUIDMILL

TEST_DIR="${2:-${0##*/}.d}"

ls -1 "${TEST_DIR%/}" | grep '^[0-9]\+-' | sort | (
    passed=0
    failed=0
    while read -r test; do
	if [ -x "${TEST_DIR%/}/$test" ]; then
	    echo -n "Executing ${TEST_DIR%/}/$test..."
	    if "${TEST_DIR%/}/$test" 1>"${TEST_DIR%/}/$test.log" 2>&1; then
		echo " OK"
		passed=$((passed + 1))
	    else
		echo " FAILED. See ${TEST_DIR%/}/$test.log for details"
		failed=$((failed + 1))
	    fi
	fi
    done
    echo ""
    if [ $failed -eq 0 ]; then
	echo "All test passed"
    else
	echo "Some tests failed"
	exit 1
    fi
)
